#pragma once
#include <d3d11.h>
#include <string>
#include <memory>

enum class ETextureType
{
	TEXT_FONT,
	ACORN_ANIME,
	UI_HEART,
	UI_DAMAGE_HEART,
	UI_CROSS,
	UI_ACORN,
	UI_STAR,
	UI_NUMBER,
	UI_GET_STAR,
	UI_GAMEPAD_BUTTON,
	UI_JUMP,
	UI_CAMERA_RESET,
	UI_CROUCHING,
	UI_DIVE,
	UI_SPIN,
	UI_TAIL_ATTACK,
	UI_DASH_JUMP,
	UI_WALL_JUMP,
	UI_HIGH_JUMP,
	UI_TURN_JUMP,
	UI_HIPDROP,
	UI_LB_BUTTON,
	UI_RB_BUTTON,
	UI_RT_BUTTON,
	UI_LT_BUTTON,
	UI_PAUSE,
	UI_TITLE_BACK,
	UI_TITLE_BACK_RED,
	UI_OPTION,
	UI_OPTION_RED,
	UI_GAME_BACK,
	UI_CAMERA_UPDOWN,
	UI_CAMERA_LEFTRIGHT,
	UI_CAMERA_SPEED,
	UI_REVERSE,
	UI_HIGH,
	UI_BACK,
	UI_SLOW,
	UI_USUALLY,
	UI_NORMAL,
	UI_ARROW,
	UI_YES,
	UI_NO,
	BLACK,
	CIRCLE_FADEIN,
	CIRCLE_FADEOUT,
	EFFECT_WALL_HIT,
	EFFECT_DASH,
	EFFECT_JUMP,
	EFFECT_STUN,
	EFFECT_ITEM_GET,
	EFFECT_SMOKE,
	EFFECT_REVIVAL,
	EFFECT_EXPLOSION,
	EFFECT_EXPLOSION2,
	EFFECT_HEART,
	EFFECT_ATTACK_HIT,
	EFFECT_ATTACK_HIT2,
	EFFECT_ATTACK_HIT3,
	EFFECT_PLAYER_HIT,
	EFFECT_GROUND_HIT,
	BOM_ANIME,
	NORMAL_BOM,
	TARGET,
	STAR_DOOR1,
	STAR_DOOR2,
	STAR_DOOR3,
	STAR_DOOR4,
	STAR_DOOR5,
	STAR_DOOR6,
	STAR_DOOR7,
	BODY1,
	BODY2,
	BODY3,
	STAGESELECT,
	STAGESELECT_BUTTON,
	STAGESELECT_SLASH,
	STAGESELECT_CHUTORIAL,
	STAGESELECT_FIRSTSTAGE,
	STAGESELECT_SECONDSTAGE,
	STAGESELECT_SELECT_ICON,
	TUTORIAL1,
	TUTORIAL2,
	TUTORIAL3,
	TUTORIAL4,
	TUTORIAL5,
	TUTORIAL6,
	TUTORIAL7,
	TUTORIAL8,
	UI_STAGE_CLEAR,
	UI_BACK_BUTTON,
	UI_NEXT,
	IMGUI_ICON_ACORN,
	IMGUI_ICON_THORNBOX,
	IMGUI_ICON_TILEBLOCK,
	IMGUI_ICON_WOODBRIDGE,
	IMGUI_ICON_STONETREE,
	IMGUI_ICON_STONEBLOCK,
	IMGUI_ICON_STUMP,
	IMGUI_ICON_GRASSWOOD,
	IMGUI_ICON_GRASSSTONE,
	IMGUI_ICON_GRASSPILLAR,
	IMGUI_ICON_NO_CLIFFBOX,
	IMGUI_ICON_SLIME,
	IMGUI_ICON_MONKEY,
	IMGUI_ICON_THORNMAN,
	IMGUI_ICON_TRIANGLE,
	IMGUI_ICON_PLANE_YELLOW,
	IMGUI_ICON_PLANE_STONE,
	IMGUI_ICON_PLANE_GREEN,
	IMGUI_ICON_PLANE_GRASS,
	IMGUI_ICON_PLANE_GRASS2,
	IMGUI_ICON_WALL_GRASS,
	IMGUI_ICON_WALL_WOOD,
	IMGUI_ICON_STAR_DOOR,
	IMGUI_ICON_TRIANGLE2,
	IMGUI_ICON_SIMPLE_GRASSBOX,
	IMGUI_ICON_GRASS_CIRCLE,
	IMGUI_ICON_GRASS_BOX_YELLOW,
	IMGUI_ICON_START_TABLE,
	IMGUI_ICON_SKY_DOME,
	IMGUI_ICON_PLAYER_START,
	IMGUI_ICON_WALL_GRASS2,
	IMGUI_ICON_PLANE_YELLOW2,
	IMGUI_ICON_BLOCK_COLLISION,
	IMGUI_ICON_BUSH,
	IMGUI_ICON_BUSH2,
	IMGUI_ICON_FORN,
	IMGUI_ICON_BUSH3,
	IMGUI_ICON_BUSH4,
	IMGUI_ICON_BUSH5,
	IMGUI_ICON_PLANT,
	IMGUI_ICON_GRASSES,
	IMGUI_ICON_FLOWER,
	IMGUI_ICON_FLOWER2,
	IMGUI_ICON_FLOWER3,
	IMGUI_ICON_ROCK,
	IMGUI_ICON_ROCK2,
	IMGUI_ICON_ROCK3,
	IMGUI_ICON_ROCK4,
	IMGUI_ICON_ROCK5,
	IMGUI_ICON_TREE,
	IMGUI_ICON_FIRSTBOSS_FIELD,
	IMGUI_ICON_FIRSTBOSS_WALL,
	IMGUI_ICON_SPHERE,
	IMGUI_ICON_TEST_BOX,
	IMGUI_ICON_WINDOWSOUTWARDS,
	IMGUI_ICON_WINDOWSOUTWARDSFRAME,
	IMGUI_ICON_WINDOWSSINGLEHIGH,
	IMGUI_ICON_WINDOWSDOUBLEHIGH,
	IMGUI_ICON_WINDOWSROUND,
	IMGUI_ICON_WINDOWSSINGLEHIGHBOARDS,
	IMGUI_ICON_DOCK,
	IMGUI_ICON_DOOR2STEP,
	IMGUI_ICON_DOOR3,
	IMGUI_ICON_DOOR4,
	IMGUI_ICON_DOOR1,
	IMGUI_ICON_HOUSE1,
	IMGUI_ICON_HOUSE2,
	IMGUI_ICON_HOUSE3,
	IMGUI_ICON_HOUSE4,
	IMGUI_ICON_ONEHOUSE1,
	IMGUI_ICON_ONEHOUSE2,
	IMGUI_ICON_ONEHOUSE3,
	IMGUI_ICON_ONEHOUSE4,
	IMGUI_ICON_BALCONY,
	IMGUI_ICON_BALCONY2,
	IMGUI_ICON_CHIMNEY,
	IMGUI_ICON_CHIMNEY2,
	IMGUI_ICON_ROOFFRAME,
	IMGUI_ICON_ROOFFRAME2,
	IMGUI_ICON_ROOFFRAME3,
	IMGUI_ICON_ROOFFRAME4,
	IMGUI_ICON_STAIRWIDE,
	IMGUI_ICON_STAIRWIDE2,
	IMGUI_ICON_ROOFFRAME5,
	IMGUI_ICON_ROOFFRAME6,
	IMGUI_ICON_VARIANT,
	IMGUI_ICON_COLUMN,
	IMGUI_ICON_ARCBIG,
	IMGUI_ICON_ARCCOMER,
	IMGUI_ICON_ARCCROSS,
	IMGUI_ICON_ARCTRIPLE,
	IMGUI_ICON_BARREL,
	IMGUI_ICON_COFFIN,
	IMGUI_ICON_COFFINCOVER,
	IMGUI_ICON_PEREKR,
	IMGUI_ICON_WOODBOX,
	IMGUI_ICON_CLAIMEDE,
	IMGUI_ICON_CLAIMEDWALL2C,
	IMGUI_ICON_DIRTDARKE,
	IMGUI_ICON_FLOOR,
	IMGUI_ICON_STONE,
	IMGUI_ICON_TOP,
	IMGUI_ICON_WALL2_1,
	IMGUI_ICON_WALL22,
	IMGUI_ICON_DAISY,
	IMGUI_ICON_SELECT_PLANE,
	IMGUI_ICON_CHAIR,
	IMGUI_ICON_CHEST,
	IMGUI_ICON_SMALLTABLE,
	IMGUI_ICON_TABLE,
	IMGUI_ICON_GREENBOOK,
	IMGUI_ICON_PURPLEBOOK,
	IMGUI_ICON_YELLOWBOOK,
	IMGUI_ICON_REDBOOK,
	IMGUI_ICON_STAGE_FRAME,
	IMGUI_ICON_STAGE_FRAME2,
	IMGUI_ICON_STAGE_FRAME3,
	IMGUI_ICON_BOSS_FIGURE,
	IMGUI_ICON_DOLLY,
	IMGUI_ICON_WOODEN,
	IMGUI_ICON_WOODEN2,
	IMGUI_ICON_WOODEN3,
	IMGUI_ICON_WOODEN4,
	IMGUI_ICON_WOODEN5,
	IMGUI_ICON_WOODEN6,
	IMGUI_ICON_WOODEN7,
	IMGUI_ICON_CHEST2,
	IMGUI_ICON_CHESTTOP2,
	IMGUI_ICON_ROCKS,
	IMGUI_ICON_STALAGS,
	IMGUI_ICON_COINS,
	IMGUI_ICON_RAIL,
	IMGUI_ICON_TEST_STAGE,
	MAX,
};

struct TextureData
{
private:
	UINT Width = 0;//テクスチャの幅
	UINT Height = 0;//テクスチャの高さ
	int LoadCount = 0;//テクスチャが読み込まれた回数。0でテクスチャリソースをアンロード
	std::shared_ptr<ID3D11ShaderResourceView> Texture;//テクスチャリソース

public:
	TextureData() {};
	TextureData(ID3D11ShaderResourceView* InTexture) 
	{
		Texture = std::shared_ptr<ID3D11ShaderResourceView>(InTexture, [](ID3D11ShaderResourceView* ptr)
		{
			if (ptr)
			{
				ptr->Release();
			}
		});

		if (!Texture)
		{
			return;
		}
		//テクスチャの幅と高さを取得
		ID3D11Resource* resource = nullptr;
		Texture->GetResource(&resource);

		if (!resource)
		{
			return;
		}
		ID3D11Texture2D* texture2d = nullptr;
		resource->QueryInterface(__uuidof(ID3D11Texture2D), (void**)&texture2d);

		if (!texture2d)
		{
			return;
		}
		D3D11_TEXTURE2D_DESC desc;
		texture2d->GetDesc(&desc);

		Width = desc.Width;
		Height = desc.Height;

		texture2d->Release();
		resource->Release();
		
		//ロードカウントを増やす
		LoadCount++;
	};

	void IncrementLoadCount() { LoadCount++; }
	void DecrementLoadCount() { LoadCount--; }
	bool IsUnloaded() const { return LoadCount <= 0; }

	std::weak_ptr<ID3D11ShaderResourceView> GetTexture() const { return Texture; }
	UINT GetWidth() const { return Width; }
	UINT GetHeight() const { return Height; }
};